print("a,b,c".split(","))
print("a b  c".split())
print("-".join(["a", "b"]))
print("  hi  ".strip(), "xxhi".strip("x"))
print("Hi".upper(), "Hi".lower(), "hi there".title())
print("hello".replace("l", "L"))
print("hello".startswith("he"), "hello".endswith("lo"))
print("hello".find("l"), "hello".count("l"))
print("5".zfill(3), "hi".center(6) + "|")
print("abc".isalpha(), "123".isdigit())
